sudo: false

language: rust

# libssh2-sys, used by git2, requires a newer cmake than exists on Travis's
# default setup.
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

rust:
  - stable
  - beta
  # Rustup + Nightly is broken right now, and I can't figure out how to get
  # allow_failures to work properly.
  # - nightly

cache: cargo

env:
  matrix:
    - JOB="test"  PROFILE=""          FEATURES=""
    - JOB="test"  PROFILE="--release" FEATURES=""
    # JOB="bench" PROFILE="--release" FEATURES=""
    - JOB="test"  PROFILE=""          FEATURES="signpost"
    - JOB="test"  PROFILE="--release" FEATURES="signpost"
    # JOB="bench" PROFILE="--release" FEATURES="signpost"

matrix:
  fast_finish: true

script: ./ci/script.sh
