sudo: false
language: rust

# To get a new enough ubuntu that has creduce.
dist: trusty

addons:
  apt:
    packages:
      - creduce
      - clang-format-3.8

rust:
  - stable
  - beta
  - nightly

cache: cargo

env:
  matrix:
    - JOB="test"  PROFILE=""          FEATURES=""
    - JOB="test"  PROFILE="--release" FEATURES=""
    # JOB="bench" PROFILE="--release" FEATURES=""
    # JOB="test"  PROFILE=""          FEATURES="signpost"
    - JOB="test"  PROFILE="--release" FEATURES="signpost"
    # JOB="bench" PROFILE="--release" FEATURES="signpost"

matrix:
  fast_finish: true
  exclude:
    - rust: beta
      env: JOB="test"  PROFILE="--release" FEATURES="signpost"
    - rust: nightly
      env: JOB="test"  PROFILE="--release" FEATURES="signpost"

script: ./ci/script.sh
