[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "A parallel, language agnostic, automatic test case reducer."
name = "preduce"
version = "0.1.0"

[[bin]]
doc = false
name = "preduce"
path = "src/bin/preduce.rs"

[dependencies]
clap = "2.23.1"
either = "1.1.0"
git2 = "0.6.4"
num_cpus = "1.3.0"
rand = "0.3.15"
tempdir = "0.3.5"

[lib]
path = "src/lib.rs"
