[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "A parallel, language agnostic, automatic test case reducer."
name = "preduce"
version = "0.1.0"
[[bin]]
doc = false
name = "preduce"
path = "src/bin/preduce.rs"

[dependencies]
clap = "2.23.1"
ctrlc = "3.0.2"
either = "1.1.0"
fixedbitset = "0.1.6"
histo = "0.1.0"
is_executable = "0.1.0"
num_cpus = "1.3.0"
rand = "0.3.15"
tempdir = "0.3.5"

[dependencies.signpost]
optional = true
version = "0.1.0"

[lib]
path = "src/lib.rs"
[profile.release]
debug = true
[target."cfg(unix)".dependencies]
libc = "0.2.26"
