[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "preduce"
version = "0.1.0"

[[bin]]
doc = false
name = "preduce"
path = "src/main.rs"

[dependencies]
rand = "0.3.15"
tempdir = "0.3.5"

[dev-dependencies]
tempfile = "2.1.5"

[lib]
path = "src/lib.rs"
