reorder_imports = true
reorder_imported_names = true
write_mode = "Overwrite"

# Style RFC Formatting
fn_args_layout = "Block"
array_layout = "Block"
where_style = "Rfc"
generics_indent = "Block"
fn_call_style = "Block"
