[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
name = "preduce_chunks_reducer"
version = "0.1.0"

[dependencies]
serde = "1.0.15"
serde_derive = "1.0.15"

[dependencies.preduce_ranges_reducer]
path = "../preduce_ranges_reducer"
version = "0.1.0"
